DE Problems and solvers
DanPuzzuoli/qiskit-aer pull request #10
Opened 2020-09-29 19:37 UTC by DanPuzzuoli

### Summary
Starting work on DE solvers and problems. Currently they seem to work and a little notebook is working, though need to work on abstract specification and add tests.

2020-10-01 21:27 UTC, DanPuzzuoli commented
Current status:

While working on introducing Problems/Solvers, realized that `OperatorModel` didn't have a sufficiently abstract definition. While trying to clear that up, realized that the frame handling was too awkwardly tied up in `OperatorModel` - obviously `OperatorModel` needs access to and needs to store frame information, but it shouldn't itself have methods for doing frame transformations.

In relation to the above:
- Created new class `BaseFrame` and concrete implementation `Frame` to store a frame operator and expose a bunch of frame handling functions from within that.
- Created a new `BaseOperatorModel` to outline exactly which methods/properties will be used by `BMDE_Problem` and `BMDE_Solver`
- Updated `OperatorModel` to inherit from `BaseOperatorModel` and to use `Frame` internally (deleted the weird/hidden `FrameFreqHelper` class)
- Initial implementations of `BMDE_Problem` and `BMDE_Solver` are usable and seem to be working within the demo notebook
- Existing tests for frame handling functionality has been moved into tests for the `Frame` object

To do:
- Clean up abstract interfaces
   - I think the main ideas are where they need to be but currently the state is just a "first pass"
- Further tests for `Frame` beyond the existing ones
- Tests for `BMDE_Problem`
- Tests for `BMDE_Solver`

2020-10-08 18:42 UTC, DanPuzzuoli commented
This PR is ready for review, see original edited comment for details.

2020-10-15 08:58 UTC, eggerdj requested changes
Looking good. Perhaps in the `BMDE_Problem_and_solver.ipynb` NB you could show the matrices after high-frequencies have been cutoff.

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +          the results will be returned in the rotating frame.
Does this raise a warning?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +        """Specify the BMDE problem, as described in the class doc string."""
Should the doc string above not be here to match with the args of the init?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +            self._user_in_frame = True
Can we raise at least a warning if the generator and the user both specify a frame?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +    :class:`BMDE_Problem`. This class serves as an an intermediary between the
```suggestion
    :class:`BMDE_Problem`. This class serves as an intermediary between the
```

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +    def t(self, new_t):
type in docstring?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +    def t(self):
return type

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +            - convert y to inner type of state
What is meant by `inner type of state`?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        """Array containing diagonalizing unitary."""
```suggestion
        """Array containing diagonalizing unitary :math:`e^{\mp tF}`."""
```
?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +    def operators_into_frame_basis(self,
why no `operators_out_of_frame_basis`?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +    def _evaluate_linear_combo(self, coeffs):
type hints.

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        ****Should put a mathematical description here***
yes please

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +class Frame(BaseFrame):
add short docsring

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        return self.frame_basis_adjoint @ to_array(op) @ self.frame_basis
Is this consistent with what is below?
```
        # go into the frame
        out = np.diag(np.exp(- t * self.frame_diag)) @ out
```
Is there not an exponential missing?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/frame.py
> +def to_array(op):
move docstring into function

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +          representing an anti-Hermitian operator :math:`F`, specifying
```suggestion
          represents an anti-Hermitian operator :math:`F`, specifying
```

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
>                   signals: Optional[Union[VectorSignal, List[Signal]]] = None,
Should this not be `BaseSignal` instead?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +                 frame: Optional[Union[Operator, np.array, Frame]] = None,
Should this not be a `BaseFrame`?

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
>          self._carrier_freqs = None
Perhaps we should specify `carrier_freqs` through the signals instead to avoid them being defined at multiple places.

2020-10-15 08:58 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +        return self._carrier_freqs
Use the signals?

2020-10-15 13:15 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
>          self._carrier_freqs = None
Agreed - removed this property

2020-10-15 13:15 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +        return self._carrier_freqs
As per above, I've removed this property entirely.

2020-10-15 13:29 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +          the results will be returned in the rotating frame.
Added a warning and a test for it.

2020-10-15 13:33 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +        """Specify the BMDE problem, as described in the class doc string."""
Added a proper doc string here.

2020-10-15 13:33 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Problems.py
> +            self._user_in_frame = True
As per above, added a warning.

2020-10-15 13:36 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +    def t(self, new_t):
Added a type hint for this.

2020-10-15 13:36 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +    def t(self):
Added a type hint for this.

2020-10-15 13:39 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +            - convert y to inner type of state
This is in reference to the terminology used in the `StateTypeConverter` class. The "inner type" is the type that the `BMDE_Solver` class works with internally, whereas the `outer type` is the type that it returns to the user, and expects the user to specify states in. E.g. if the BMDE represents the vectorized lindblad equation, the outer type will be a 2d array (the user works with density matrices), but the inner type will be a 1d array (the "state" of the DE is the vectorized density matrix).

2020-10-15 13:44 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        """Array containing diagonalizing unitary."""
This is the unitary that diagonalizes F. I've updated the doc string to explain this more clearly.

2020-10-15 13:46 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +    def operators_into_frame_basis(self,
Added.

2020-10-15 13:47 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +    def _evaluate_linear_combo(self, coeffs):
Added.

2020-10-15 15:06 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        ****Should put a mathematical description here***
Added - this requires a huge amount of explanation but it needs to be explained somewhere.

2020-10-15 15:23 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +class Frame(BaseFrame):
Added.

2020-10-15 15:27 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +        return self.frame_basis_adjoint @ to_array(op) @ self.frame_basis
This function is just a basis change, so no exponentiation required.

2020-10-15 15:27 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/frame.py
> +def to_array(op):
Done.

2020-10-15 15:29 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
>                   signals: Optional[Union[VectorSignal, List[Signal]]] = None,
Yes. I've changed it to `BaseSignal`. I think it makes sense to make a `BaseVectorSignal` as well, but we can do this as a separate PR.

2020-10-15 15:30 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +                 frame: Optional[Union[Operator, np.array, Frame]] = None,
Yep, changed.

2020-10-15 15:30 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
>          self._carrier_freqs = None
Agreed - got rid of the internally stored carrier frequencies in `OperatorModel`.

2020-10-15 15:31 UTC, DanPuzzuoli commented on qiskit/providers/aer/pulse_new/models/operator_models.py
> +        return self._carrier_freqs
Agreed - got rid of the internally stored carrier frequencies in `OperatorModel`.

2020-10-15 16:02 UTC, eggerdj approved these changes
Looks good. One minor thing in a docstring.

2020-10-15 16:02 UTC, eggerdj commented on qiskit/providers/aer/pulse_new/de/DE_Solvers.py
> +            - convert y to inner type of state
perhaps?
```suggestion
            - convert y to inner type of state which the solver works with
```

2020-10-15 17:06 UTC, merged